version: "1.0"
info:
  model: int-scaffold
packages:
- name: ExtProjProject
  gitServerName: GH_SK
  gitUrl: https://github.com/santhu736852
  gitUsername: santhu736852
  gitBranch: main
services:
- serviceName: project.extproj.integrations:TestEDI2
  packages:
  - name: ExtProjProject
    version: "1.0"
- serviceName: pub.math:addInts
  packages:
  - name: WmPublic
    version: 12.1.0.0.1143
